apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: hello-ws
---
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: hello-ws
  namespace: hello-ws
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hello-ws
status:
  loadBalancer: {}
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hello-ws
  name: hello-ws
  namespace: hello-ws
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-ws
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-ws
    spec:
      containers:
      - image: cless91/hello-ws
        name: hello-ws
        env:
        - name: FLASK_RUN_HOST
          value: "0.0.0.0"
        - name: FLASK_RUN_PORT
          value: "80"
---
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-ingress
  namespace: hello-ws
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: hello-ws
          servicePort: 80
        path: /hello
        pathType: ImplementationSpecific
