apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: hello-ws-canary
---
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: hello-ws-canary
  namespace: hello-ws-canary
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hello-ws-canary
status:
  loadBalancer: {}
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hello-ws-canary
  name: hello-ws-canary
  namespace: hello-ws-canary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-ws-canary
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-ws-canary
    spec:
      containers:
      - image: cless91/hello-ws:v2
        name: hello-ws-canary
        env:
        - name: FLASK_RUN_HOST
          value: "0.0.0.0"
        - name: FLASK_RUN_PORT
          value: "80"
---
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "80"
  name: hello-ingress-canary
  namespace: hello-ws-canary
spec:
  rules:
  - host: localhost
    http:
      paths:
      - backend:
          serviceName: hello-ws-canary
          servicePort: 80
        path: /hello
        pathType: ImplementationSpecific
